/**
 * WorldClock timezone library
 * 60+ popular timezones with flag emoji, country, city, and IANA tz identifier.
 * Used in the Add Widget modal search/picker.
 */

export const TIMEZONES = [
  // ── Asia ────────────────────────────────────────────────────────────────
  { flag: '🇮🇳', country: 'India',          city: 'Kolkata',        tz: 'Asia/Kolkata'                    },
  { flag: '🇯🇵', country: 'Japan',           city: 'Tokyo',          tz: 'Asia/Tokyo'                      },
  { flag: '🇨🇳', country: 'China',           city: 'Shanghai',       tz: 'Asia/Shanghai'                   },
  { flag: '🇭🇰', country: 'Hong Kong',       city: 'Hong Kong',      tz: 'Asia/Hong_Kong'                  },
  { flag: '🇹🇼', country: 'Taiwan',          city: 'Taipei',         tz: 'Asia/Taipei'                     },
  { flag: '🇰🇷', country: 'South Korea',     city: 'Seoul',          tz: 'Asia/Seoul'                      },
  { flag: '🇸🇬', country: 'Singapore',       city: 'Singapore',      tz: 'Asia/Singapore'                  },
  { flag: '🇲🇾', country: 'Malaysia',        city: 'Kuala Lumpur',   tz: 'Asia/Kuala_Lumpur'               },
  { flag: '🇹🇭', country: 'Thailand',        city: 'Bangkok',        tz: 'Asia/Bangkok'                    },
  { flag: '🇻🇳', country: 'Vietnam',         city: 'Ho Chi Minh',    tz: 'Asia/Ho_Chi_Minh'                },
  { flag: '🇵🇭', country: 'Philippines',     city: 'Manila',         tz: 'Asia/Manila'                     },
  { flag: '🇮🇩', country: 'Indonesia',       city: 'Jakarta',        tz: 'Asia/Jakarta'                    },
  { flag: '🇧🇩', country: 'Bangladesh',      city: 'Dhaka',          tz: 'Asia/Dhaka'                      },
  { flag: '🇵🇰', country: 'Pakistan',        city: 'Karachi',        tz: 'Asia/Karachi'                    },
  { flag: '🇱🇰', country: 'Sri Lanka',       city: 'Colombo',        tz: 'Asia/Colombo'                    },
  { flag: '🇳🇵', country: 'Nepal',           city: 'Kathmandu',      tz: 'Asia/Kathmandu'                  },
  { flag: '🇦🇫', country: 'Afghanistan',     city: 'Kabul',          tz: 'Asia/Kabul'                      },
  { flag: '🇺🇿', country: 'Uzbekistan',      city: 'Tashkent',       tz: 'Asia/Tashkent'                   },
  { flag: '🇰🇿', country: 'Kazakhstan',      city: 'Almaty',         tz: 'Asia/Almaty'                     },
  { flag: '🇦🇿', country: 'Azerbaijan',      city: 'Baku',           tz: 'Asia/Baku'                       },
  { flag: '🇦🇲', country: 'Armenia',         city: 'Yerevan',        tz: 'Asia/Yerevan'                    },
  { flag: '🇬🇪', country: 'Georgia',         city: 'Tbilisi',        tz: 'Asia/Tbilisi'                    },
  { flag: '🇦🇪', country: 'UAE',             city: 'Dubai',          tz: 'Asia/Dubai'                      },
  { flag: '🇸🇦', country: 'Saudi Arabia',    city: 'Riyadh',         tz: 'Asia/Riyadh'                     },
  { flag: '🇶🇦', country: 'Qatar',           city: 'Doha',           tz: 'Asia/Qatar'                      },
  { flag: '🇰🇼', country: 'Kuwait',          city: 'Kuwait City',    tz: 'Asia/Kuwait'                     },
  { flag: '🇮🇱', country: 'Israel',          city: 'Jerusalem',      tz: 'Asia/Jerusalem'                  },
  { flag: '🇮🇶', country: 'Iraq',            city: 'Baghdad',        tz: 'Asia/Baghdad'                    },
  { flag: '🇮🇷', country: 'Iran',            city: 'Tehran',         tz: 'Asia/Tehran'                     },
  { flag: '🇲🇲', country: 'Myanmar',         city: 'Yangon',         tz: 'Asia/Yangon'                     },

  // ── Europe ──────────────────────────────────────────────────────────────
  { flag: '🇬🇧', country: 'United Kingdom',  city: 'London',         tz: 'Europe/London'                   },
  { flag: '🇩🇪', country: 'Germany',         city: 'Berlin',         tz: 'Europe/Berlin'                   },
  { flag: '🇫🇷', country: 'France',          city: 'Paris',          tz: 'Europe/Paris'                    },
  { flag: '🇮🇹', country: 'Italy',           city: 'Rome',           tz: 'Europe/Rome'                     },
  { flag: '🇪🇸', country: 'Spain',           city: 'Madrid',         tz: 'Europe/Madrid'                   },
  { flag: '🇳🇱', country: 'Netherlands',     city: 'Amsterdam',      tz: 'Europe/Amsterdam'                },
  { flag: '🇧🇪', country: 'Belgium',         city: 'Brussels',       tz: 'Europe/Brussels'                 },
  { flag: '🇨🇭', country: 'Switzerland',     city: 'Zurich',         tz: 'Europe/Zurich'                   },
  { flag: '🇦🇹', country: 'Austria',         city: 'Vienna',         tz: 'Europe/Vienna'                   },
  { flag: '🇸🇪', country: 'Sweden',          city: 'Stockholm',      tz: 'Europe/Stockholm'                },
  { flag: '🇳🇴', country: 'Norway',          city: 'Oslo',           tz: 'Europe/Oslo'                     },
  { flag: '🇩🇰', country: 'Denmark',         city: 'Copenhagen',     tz: 'Europe/Copenhagen'               },
  { flag: '🇫🇮', country: 'Finland',         city: 'Helsinki',       tz: 'Europe/Helsinki'                 },
  { flag: '🇵🇱', country: 'Poland',          city: 'Warsaw',         tz: 'Europe/Warsaw'                   },
  { flag: '🇨🇿', country: 'Czech Republic',  city: 'Prague',         tz: 'Europe/Prague'                   },
  { flag: '🇭🇺', country: 'Hungary',         city: 'Budapest',       tz: 'Europe/Budapest'                 },
  { flag: '🇷🇴', country: 'Romania',         city: 'Bucharest',      tz: 'Europe/Bucharest'                },
  { flag: '🇧🇬', country: 'Bulgaria',        city: 'Sofia',          tz: 'Europe/Sofia'                    },
  { flag: '🇬🇷', country: 'Greece',          city: 'Athens',         tz: 'Europe/Athens'                   },
  { flag: '🇵🇹', country: 'Portugal',        city: 'Lisbon',         tz: 'Europe/Lisbon'                   },
  { flag: '🇮🇪', country: 'Ireland',         city: 'Dublin',         tz: 'Europe/Dublin'                   },
  { flag: '🇷🇺', country: 'Russia',          city: 'Moscow',         tz: 'Europe/Moscow'                   },
  { flag: '🇷🇺', country: 'Russia',          city: 'Vladivostok',    tz: 'Asia/Vladivostok'                },
  { flag: '🇺🇦', country: 'Ukraine',         city: 'Kyiv',           tz: 'Europe/Kyiv'                     },
  { flag: '🇹🇷', country: 'Turkey',          city: 'Istanbul',       tz: 'Europe/Istanbul'                 },

  // ── Americas ────────────────────────────────────────────────────────────
  { flag: '🇺🇸', country: 'United States',   city: 'New York',       tz: 'America/New_York'                },
  { flag: '🇺🇸', country: 'United States',   city: 'Chicago',        tz: 'America/Chicago'                 },
  { flag: '🇺🇸', country: 'United States',   city: 'Denver',         tz: 'America/Denver'                  },
  { flag: '🇺🇸', country: 'United States',   city: 'Los Angeles',    tz: 'America/Los_Angeles'             },
  { flag: '🇺🇸', country: 'United States',   city: 'Anchorage',      tz: 'America/Anchorage'               },
  { flag: '🇺🇸', country: 'United States',   city: 'Honolulu',       tz: 'Pacific/Honolulu'                },
  { flag: '🇨🇦', country: 'Canada',          city: 'Toronto',        tz: 'America/Toronto'                 },
  { flag: '🇨🇦', country: 'Canada',          city: 'Vancouver',      tz: 'America/Vancouver'               },
  { flag: '🇨🇦', country: 'Canada',          city: 'Halifax',        tz: 'America/Halifax'                 },
  { flag: '🇲🇽', country: 'Mexico',          city: 'Mexico City',    tz: 'America/Mexico_City'             },
  { flag: '🇧🇷', country: 'Brazil',          city: 'São Paulo',      tz: 'America/Sao_Paulo'               },
  { flag: '🇧🇷', country: 'Brazil',          city: 'Manaus',         tz: 'America/Manaus'                  },
  { flag: '🇦🇷', country: 'Argentina',       city: 'Buenos Aires',   tz: 'America/Argentina/Buenos_Aires'  },
  { flag: '🇨🇱', country: 'Chile',           city: 'Santiago',       tz: 'America/Santiago'                },
  { flag: '🇨🇴', country: 'Colombia',        city: 'Bogotá',         tz: 'America/Bogota'                  },
  { flag: '🇵🇪', country: 'Peru',            city: 'Lima',           tz: 'America/Lima'                    },
  { flag: '🇻🇪', country: 'Venezuela',       city: 'Caracas',        tz: 'America/Caracas'                 },
  { flag: '🇨🇺', country: 'Cuba',            city: 'Havana',         tz: 'America/Havana'                  },

  // ── Africa ──────────────────────────────────────────────────────────────
  { flag: '🇿🇦', country: 'South Africa',    city: 'Johannesburg',   tz: 'Africa/Johannesburg'             },
  { flag: '🇳🇬', country: 'Nigeria',         city: 'Lagos',          tz: 'Africa/Lagos'                    },
  { flag: '🇪🇬', country: 'Egypt',           city: 'Cairo',          tz: 'Africa/Cairo'                    },
  { flag: '🇰🇪', country: 'Kenya',           city: 'Nairobi',        tz: 'Africa/Nairobi'                  },
  { flag: '🇪🇹', country: 'Ethiopia',        city: 'Addis Ababa',    tz: 'Africa/Addis_Ababa'              },
  { flag: '🇬🇭', country: 'Ghana',           city: 'Accra',          tz: 'Africa/Accra'                    },
  { flag: '🇹🇿', country: 'Tanzania',        city: 'Dar es Salaam',  tz: 'Africa/Dar_es_Salaam'            },
  { flag: '🇲🇦', country: 'Morocco',         city: 'Casablanca',     tz: 'Africa/Casablanca'               },
  { flag: '🇩🇿', country: 'Algeria',         city: 'Algiers',        tz: 'Africa/Algiers'                  },

  // ── Pacific & Oceania ────────────────────────────────────────────────────
  { flag: '🇦🇺', country: 'Australia',       city: 'Sydney',         tz: 'Australia/Sydney'                },
  { flag: '🇦🇺', country: 'Australia',       city: 'Melbourne',      tz: 'Australia/Melbourne'             },
  { flag: '🇦🇺', country: 'Australia',       city: 'Brisbane',       tz: 'Australia/Brisbane'              },
  { flag: '🇦🇺', country: 'Australia',       city: 'Perth',          tz: 'Australia/Perth'                 },
  { flag: '🇦🇺', country: 'Australia',       city: 'Adelaide',       tz: 'Australia/Adelaide'              },
  { flag: '🇳🇿', country: 'New Zealand',     city: 'Auckland',       tz: 'Pacific/Auckland'                },
  { flag: '🇫🇯', country: 'Fiji',            city: 'Suva',           tz: 'Pacific/Fiji'                    },

  // ── UTC ──────────────────────────────────────────────────────────────────
  { flag: '🌐', country: 'UTC',              city: 'Universal Time', tz: 'UTC'                             },
]
